name: simple_note_taker
description: Flutter project.
publish_to: 'none'
version: 2.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  shared_preferences: ^2.5.3
  share_plus: ^10.0.0
  url_launcher: ^6.3.1
  easy_dynamic_theme: ^2.3.1
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  share_handler: ^0.0.23
  cupertino_icons: ^1.0.2
  dynamic_color: ^1.7.0
  jiffy: ^6.4.3
  permission_handler: ^11.3.0
  fluttertoast: ^8.2.12
  async_redux: ^25.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/
