name: simple_note_taker
description: Flutter project.
publish_to: 'none'
version: 2.0.2

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http:
  shared_preferences:
  share:
  url_launcher:
  easy_dynamic_theme:
  sqflite:
  path_provider:
  detectable_text_field: ^2.0.3
  share_handler:
  cupertino_icons: ^1.0.2
  dynamic_color: ^1.7.0
  jiffy:
  permission_handler: ^11.3.0
  fluttertoast:
  file_picker: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/
